# Generated by Django 5.1.6 on 2025-02-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=128)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
    ]
