# Generated by Django 5.1.4 on 2025-02-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
