# Generated by Django 5.1.6 on 2025-02-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_examination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
